In [4]:
from collections import defaultdict
from surprise import SVD
from surprise import Reader, Dataset
import pandas as pd
from surprise.model_selection import KFold
from surprise import dump
from surprise import accuracy
from surprise.model_selection import cross_validate
import pymysql
import csv
from datetime import datetime #,timedelta
import time
import surprise

##db
db = pymysql.connect(host='###', user='###', password='###' ,db='###', charset='utf8')

# prepare a cursor object using cursor() method
cursor = db.cursor()
# execute SQL query using execute() method.
cursor.execute("SELECT VERSION()")
# Fetch a single row using fetchone() method.
data = cursor.fetchone()
print("Database version : %s " % data)


def get_top_n(predictions, n=10):

    # First map the predictions to each user.
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))
    

    # Then sort the predictions for each user and retrieve the k highest ones.
    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n

#csv형식의 태그 테이블(usertag) 읽기, 읽은 후 user,item,rate에 값 저장
sql = "select * from usertag"
cursor.execute("set names utf8")
cursor.execute(sql)
#result = cursor.fetchall() 다 읽기 
df = pd.read_sql(sql,db)


df['tag_id']= df['tag_id'].astype(str)
df['user_id']= df['user_id'].astype(str)
#df['userTag_count']= df['userTag_count'].astype(float)

print("df.shape={}".format(df.shape))
print(df.dtypes)
print(df.head())
print(df.describe(include='all'))

#reader class using only the rating parameter
reader= Reader(rating_scale=(0.0, 5.0))

#arranging dataframe
data= Dataset.load_from_df(df[['user_id', 'tag_id', 'userTag_count']], reader)

#build full trainset and use cross validation for evaluation
trainset= data.build_full_trainset()

algo = SVD()
algo.fit(trainset)

##db
db = pymysql.connect(host='###', user='###', password='###' ,db='###', charset='utf8')

# prepare a cursor object using cursor() method
cursor = db.cursor()
# execute SQL query using execute() method.
cursor.execute("SELECT VERSION()")
# Fetch a single row using fetchone() method.
data = cursor.fetchone()
print("Database version : %s " % data)

testset = trainset.build_anti_testset()
predictions = algo.test(testset)
accuracy.rmse(predictions)
top_n = get_top_n(predictions, n=5)

for uid, user_ratings in top_n.items():
    #sql= "UPDATE `cftable SET user_id='%s' cf_id='%s' rate='%s'" % (uid,uid,user_ratings)
    for (iid, rating) in user_ratings:
        print(uid,iid,rating)
        #sql= "UPDATE `cftable SET user_id='%s' cf_id='%s' rate='%s'" % (uid,iid,rating)
        #sql= "INSERT INTO cftable (user_id,cf_id,rate) VALUES (%s,%s,%s)" 
        #cursor.execute(sql, (int(uid),int(iid),float(rating)))
        db.commit()
db.close()
print("완료")

Database version : 5.7.28-0ubuntu0.18.04.4
df.shape=(581, 5)
userTag_id                int64
user_id                  object
tag_id                   object
userTag_count             int64
time             datetime64[ns]
dtype: object
   userTag_id user_id tag_id  userTag_count                time
0           1       2  52076              2 2019-12-30 16:47:50
1           2       2  50903              2 2019-12-30 16:47:50
2           3       2  50375              2 2019-12-30 16:47:50
3           4       2  20371              2 2019-12-30 16:47:57
4           5       2  52071              2 2019-12-30 16:47:57
        userTag_id user_id tag_id  userTag_count                 time
count   581.000000     581    581     581.000000                  581
unique         NaN       5    384            NaN                  184
top            NaN       3  20627            NaN  2019-12-30 16:52:36
freq           NaN     144      4            NaN                    9
first          NaN     NaN    NaN            NaN  2019-12-30 16:47:50
last           NaN     NaN    NaN            NaN  2019-12-30 16:54:44
mean    291.000000     NaN    NaN       1.306368                  NaN
std     167.864529     NaN    NaN       0.716152                  NaN
min       1.000000     NaN    NaN       1.000000                  NaN
25%     146.000000     NaN    NaN       1.000000                  NaN
50%     291.000000     NaN    NaN       1.000000                  NaN
75%     436.000000     NaN    NaN       1.000000                  NaN
max     581.000000     NaN    NaN       5.000000                  NaN
Database version : 5.7.28-0ubuntu0.18.04.4
RMSE: 0.1743
2 11363 2.1892866688714503
2 52954 2.1354636494136408
2 52952 2.114053013696554
2 51852 1.9088063385949807
2 53473 1.8442629843426421
4 10711 1.6421762229707002
4 11211 1.6365982650956807
4 52072 1.6331737505025963
4 52631 1.5844184656794411
4 10151 1.5836744088765813
3 11363 2.060988927801892
3 52954 1.8341578070113829
3 52952 1.7401800625239878
3 53210 1.558134429879448
3 51852 1.5416154780061677
1 10303 2.0259651056248917
1 31169 1.7889671295268617
1 20760 1.6622275140047709
1 50458 1.6351069297223337
1 52072 1.6205073858580659
5 52042 1.7341687826621492
5 31169 1.7224023101203465
5 52072 1.6729844976702144
5 52461 1.6667557416025138
5 50903 1.6526937433464415
완료

In [5]:
#pred = algo.predict("1", "10303", r_ui=0, verbose=True)
#pred = algo.predict("2", "50458", r_ui=4, verbose=True)
#pred = algo.predict("3", "52954", r_ui=0, verbose=True)
#pred = algo.predict("4", "50458", r_ui=3, verbose=True)
#pred = algo.predict("5", "31169", r_ui=0, verbose=True)

user: 1          item: 10303      r_ui = 0.00   est = 2.03   {'was_impossible': False}
user: 2          item: 50458      r_ui = 4.00   est = 2.11   {'was_impossible': False}
user: 3          item: 52954      r_ui = 0.00   est = 1.83   {'was_impossible': False}
user: 4          item: 50458      r_ui = 3.00   est = 1.92   {'was_impossible': False}
user: 5          item: 31169      r_ui = 0.00   est = 1.72   {'was_impossible': False}